version: "3"
services: 
  node-app:
    volumes: 
      - ./:/app
      - /app/node_modules
    build: 
      context: . 
      args: 
        NODE_ENV: development  
    ports: 
      - "3000:3000"
    environment: 
      - NODE_ENV=development 
    command: npm run dev